name: Android Build, Test, and Release

on:
  workflow_dispatch: # Allows manual triggering
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'android/**'
      - 'shared/**'
      - '.github/workflows/android-build.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'android/**'
      - 'shared/**'
      - '.github/workflows/android-build.yml'
    tags:
      - 'v*' # Run workflow when a version tag is pushed

jobs:
  build_test_release_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          lfs: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        working-directory: ./android
        run: chmod +x gradlew

      - name: Run Detekt
        working-directory: ./android
        run: ./gradlew detekt

      - name: Run Android Lint
        working-directory: ./android
        run: ./gradlew :app:lintDebug

      - name: Run unit tests
        working-directory: ./android
        run: ./gradlew :app:testDebugUnitTest
        env:
          MAESTRO_KEY: ${{ secrets.MAESTRO_KEY }}

      - name: Run Screenshot Tests
        working-directory: ./android
        run: ./gradlew :app:screenshotTests

      - name: Create Screenshot Archive
        working-directory: ./android
        run: |
          mkdir -p screenshot_artifacts
          cp -R app/build/outputs/compose_screenshot_test/* screenshot_artifacts/ || echo "No screenshots generated"
          cp -R app/build/reports/compose_screenshot_test/* screenshot_artifacts/ || echo "No reports available"
          zip -r snapshots.zip screenshot_artifacts

      - name: Build Release AAB
        working-directory: ./android
        run: ./gradlew :app:bundleRelease uploadCrashlyticsMappingFileRelease

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: ScaffoldPRO.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
          retention-days: 30
          
      - name: Upload Screenshot Results
        uses: actions/upload-artifact@v4
        with:
          name: android-snapshots
          path: android/snapshots.zip
          retention-days: 30