name: iOS Build and Test

on:
  workflow_dispatch: # Allows manual triggering
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'ios/**'
      - 'shared/**'
      - '.github/workflows/ios-build.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'ios/**'
      - 'shared/**'
      - '.github/workflows/ios-build.yml'
    tags:
      - 'v*' # Run workflow when a version tag is pushed

jobs:
  build_and_test_ios:
    runs-on: macos-latest # Or your preferred macOS runner
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer # Adjust Xcode version as needed
      DETOX_IOS_SCHEME: ${{ secrets.DETOX_IOS_SCHEME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # If you use submodules like scaffold_project
          lfs: true # Ensure LFS objects are fetched

      - name: Select Xcode version
        run: sudo xcode-select -s $DEVELOPER_DIR

      - name: Cache Swift Package Manager dependencies
        uses: actions/cache@v4
        with:
          path: ios/.build # Path to SPM build artifacts
          key: ${{ runner.os }}-spm-${{ hashFiles('ios/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Resolve Swift Packages
        working-directory: ./ios
        run: xcodebuild -resolvePackageDependencies -scheme ScaffoldPRO -project ScaffoldPRO.xcodeproj # Adjust project/scheme name

      - name: Run iOS Tests
        working-directory: ./ios
        run: |
          xcodebuild test -scheme ScaffoldPRO \
            -project ScaffoldPRO.xcodeproj \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max,OS=latest' \
            CODE_SIGNING_ALLOWED=NO
          # Adjust scheme, project, and destination as needed
        env:
          MAESTRO_KEY: ${{ secrets.MAESTRO_KEY }}

      - name: Archive iOS Build
        if: success()
        working-directory: ./ios
        run: |
          xcodebuild archive -project ScaffoldPRO.xcodeproj \
            -scheme ScaffoldPRO \
            -archivePath build/archive/ScaffoldPRO.xcarchive \
            SKIP_INSTALL=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Export IPA
        if: success()
        working-directory: ./ios
        run: |
          # Create exportOptions.plist
          cat > exportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
          </dict>
          </plist>
          EOL
          
          xcodebuild -exportArchive \
            -archivePath build/archive/ScaffoldPRO.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist exportOptions.plist

      - name: Run Snapshot Tests
        working-directory: ./ios
        run: |
          # Create a snapshots directory
          mkdir -p snapshots
          
          # Run the snapshot tests
          xcodebuild test -scheme ScaffoldPROSnapshotTests \
            -project ScaffoldPRO.xcodeproj \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max,OS=latest' \
            CODE_SIGNING_ALLOWED=NO
          
          # Copy snapshot results
          cp -R derivedData/Logs/Test/*.xcresult snapshots/ || echo "No snapshot results found"
          
          # Create archive
          zip -r snapshots.zip snapshots

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ScaffoldPRO.ipa
          path: ./ios/build/ipa/ScaffoldPRO.ipa
          retention-days: 30
          
      - name: Upload Snapshots
        uses: actions/upload-artifact@v4
        with:
          name: ios-snapshots
          path: ./ios/snapshots.zip
          retention-days: 30

      - name: Upload USDZ Models
        uses: actions/upload-artifact@v4
        with:
          name: usdz-models
          path: ./ios/ScaffoldPRO/Assets.xcassets/AR\ Resources/*.usdz
          if-no-files-found: ignore
          retention-days: 30

      - name: Upload ContrastKit Report
        uses: actions/upload-artifact@v4
        with:
          name: contrastkit.html
          path: ./ios/build/reports/contrastkit/contrastkit.html
          if-no-files-found: ignore
          retention-days: 30
          
      - name: Upload dSYM Symbols to Crashlytics
        if: success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        working-directory: ./ios
        run: |
          # Upload debug symbols to Firebase Crashlytics
          xcrun upload-symbols -gsp GoogleService-Info.plist \
            -p ios \
            build/archive/ScaffoldPRO.xcarchive/dSYMs