name: Smoke Tests

on:
  workflow_dispatch: # Allows manual triggering
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'
  push:
    branches:
      - main
      - develop
      - 'v*.*-rc*-gold'

jobs:
  smoke_test_ios:
    name: iOS Smoke Tests
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Select Xcode version
        run: sudo xcode-select -s $DEVELOPER_DIR

      - name: Setup Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Smoke Tests
        working-directory: ./ios
        run: |
          fastlane smoke_test
        env:
          DETOX_IOS_SCHEME: ${{ secrets.DETOX_IOS_SCHEME }}
          MAESTRO_KEY: ${{ secrets.MAESTRO_KEY }}
      
      - name: Upload Smoke Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-smoke-test-results
          path: ./ios/fastlane/test_output/smoke
          retention-days: 7

  smoke_test_android:
    name: Android Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        working-directory: ./android
        run: chmod +x gradlew

      - name: Run Smoke Tests
        working-directory: ./android
        run: |
          ./gradlew :app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.scaffoldpro.app.SmokeTestSuite
        env:
          MAESTRO_KEY: ${{ secrets.MAESTRO_KEY }}
      
      - name: Upload Smoke Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-smoke-test-results
          path: ./android/app/build/reports/androidTests/connected
          retention-days: 7